services:
  collaborative-code-editor-service:
    container_name: collaborative-code-editor-service
    build:
      context: .
      target: development
    volumes:
      - ./src:/usr/src/app/src
      - ./tmp/keys:/usr/src/app/keys
      - ./bin:/usr/src/app/bin
    ports:
      - 3030:3000
    command: npm run prestart && npm run start:dev
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    container_name: collaborative-code-editor-service-postgres
    build: postgres
    environment:
      PGDATA: /var/lib/postgresql@17/data
    volumes:
      - ./tmp/pgdata/collaborative-code-editor-service:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d postgres']
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
      - 5432:5432
